name : My First Workflow

on : [push, pull_request]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello, GitHub Action"

      - name: Print message 2
        run: echo "Sneha Khanna"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Goodbye from second job"

  deploy-app:
    runs-on: ubuntu-latest
    needs: [say-hello, say-bye]

    steps:
      - name: Checkout code
        uses:  actions/checkout@v4

      - name: Build Application
        run: echo "Building the Application..."

      - name: Deploy Application
        run: echo "Deploying the Application..."